name: mkdocs-build
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  docs-strict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          # Uncomment if PR build checks fail duye to new plugin needing full commit history. Will slow down build
          # fetch-depth: 0
          # sparse-checkout: |
          #   docs
          #   includes
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Setup Python environment
        run: pip install -r requirements.txt
      - name: Build docs with --strict
        run: make build-docs
